### PR TITLE
Add extra font sizes for interface list and tooltips

### PR DESCRIPTION
**Pull request by SSyl**
I found the font size options for the inventory/bank item list to be either way too small or just a little too big when playing on my TV, so I went ahead and made an extra option for a size between the setting being on or off.

What I've done is I've changed the setting under BetterUI (General Interface) -> "Use bigger font size in the UI item lists" (aka the `biggerSkin` setting) to a dropdown list. The options are now Default, Bigger, and Biggest.

- Default is what used to be the default option, which was when `biggerSkin` was set to false.
- Biggest is what used to be the option when `biggerSkin` was set to true.
- Bigger is between Biggest and Default and is a 6pt font reduction across the board compared to Biggest. I've also adjusted the icons for the font change in the list.

I've tested it for the inventory and banking lists, switched settings, etc. and it works great.

### CODE REVIEW

**Comment by SSyl** [comment]
Oh, one thing I forgot/wasn't sure how to do is add a check to convert any existing biggerSkin saved variable from the true/false boolean to their corresponding Default/Biggest setting.

Currently it works just fine if you load it with existing saved data, but if it was set to true it'll revert to the default setting. A user will just need to go back into the settings and choose either Big or Biggest to change their UI to the increase version again.

**Comment by SSyl** [comment]
I added tooltip size options as well. Now there's three options for tooltip sizes plus the "default" size, which is the largest of them all.

I also changed biggerSkin to just skinSize and changed the sizes to Default, Medium, Large, with Default being the smallest.

The default option for both settings are exactly the same as what the default originally was before this pull request.

**Comment by SSyl** [comment]
The UI lists font sizes I feel are at a good place at this point. The tooltips font sizes probably need a bit of tweaking to get that "perfect" look, but there's no visual bugs or glitches with the text that I've found so it's good to go.

Also, since the settings variables were changed from a boolean to an array/list, anyone who would download this update would revert back to the default list and tooltip sizes. It can be fixed by just going back to the addon settings and selecting whatever you want from the dropdown list, but it's worth noting.

There might be a way to convert their existing saved variables to the drop down list variables, but I haven't dug into it.

**Comment by goobsnake** [comment]
Made a minor change but everything looks good. Thanks for the contribution, these features will go out in the next release.

**Pull request merged**
